### ISSUE TITLE
Permissions issue causing failed builds

### ISSUE THREAD

**Issue by madisonbullard** [rave-cafe/rave-cafe#13]
https://github.com/rave-cafe/rave-cafe/actions/runs/5318261323/jobs/9629562702

@daltn Did anything change with the repo settings that might've triggered this? After a quick google, it looks like there's a lot of similar cases, so hopefully we can track down a solve without much hassle.

It started failing when I committed the `yarn.lock` file, which conflicts with our `package-lock.json` file. Seems unlikely, but perhaps we need to clear some cache somewhere to fully purge our deploy pipeline of that conflict.

I would think a more straightforward permissioning issue is at the root of this, tho.

**Comment by daltn** [comment]
hmmm yeah i've been looking into this and I'll continue noodling on it
