### ISSUE TITLE
Squash merge or merge commit?

### ISSUE THREAD

**Issue by madisonbullard** [rave-cafe/rave-cafe#5]
I prefer to squash-merge PRs to keep commit history clean. For example, take our current commit history, which factors in our initial commit + first PR:
```
850d11a Merge pull request #1 from rave-cafe/madisonbullard/strict-mode
20e407b fix type errors
016abf2 Enable TS strict mode
6d24e5d Initial commit
```

With squash-merging, this could look like:
```
850d11a Enable TS strict mode (#1)
6d24e5d Initial commit
```

Just a personal preference, not tied to it if there is any opposition. What do you think @daltn?

**Comment by madisonbullard** [comment]
To be clear, not suggesting we alter the current commit history at all. This would just be a consideration moving forward

**Comment by daltn** [comment]
I'm down with the squash and merge for a clean commit history. Can that option be enabled on the PR review UI or is it a repo setting? I remember seeing it somewhere

**Comment by madisonbullard** [comment]
@daltn I think its an option under repo "Settings > Branches" then scroll down and they show something about which merge actions are permitted

**Comment by daltn** [comment]
<img width="789" alt="Screenshot 2023-06-15 at 5 53 36 PM" src="https://github.com/rave-cafe/rave-cafe/assets/6643356/58af7532-dafd-4489-8665-1fc8cb2d751d">
found it :) it is under the merging of each PR into the main branch
